#define MOTOR_SPEED_CONTROL_PIN 5
#define MOTOR_DIRECTION_CONTROL_PIN 4
#define END_STOP_TOP 7
#define END_STOP_BOTTOM 8
#define MAX_ACTION_DURATION 10000
#define PHOTORESISTOR_PIN 0
#define BUTTONS_PINS 7
